id: I4D1DB116
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1657
  ocr_info:
    timestamp: 03/21/23T14:11:04
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 22:31:34.851518+00:00
last_modified: 2024-02-28 22:31:34.851525+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1657
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1657
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སཾ་བོད་སྐད་གཉིས་ཤན་སྦྱར་ཚིག་མཛོད།
  languages:
  - bo
  - sa
statistics:
  ocr_word_mean_confidence_index: 0.815855368085285
  ocr_word_median_confidence_index: 0.92
bases:
  I3CN1659:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1659
      total_pages: 356
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1659.txt
    statistics:
      ocr_word_median_confidence_index: 0.92
      ocr_word_mean_confidence_index: 0.815855368085285
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
